// Shape counts //<>//
final char SHAPE_COUNT_ONE = '1';
final char SHAPE_COUNT_TWO = '2';
final char SHAPE_COUNT_THREE = '3';
final char[] SHAPE_COUNTS = {SHAPE_COUNT_ONE, SHAPE_COUNT_TWO, SHAPE_COUNT_THREE};

// Shape colors
final char SHAPE_COLOR_RED = 'R';
final char SHAPE_COLOR_GREEN = 'G';
final char SHAPE_COLOR_BLUE = 'B';
final char[] SHAPE_COLORS = {SHAPE_COLOR_RED, SHAPE_COLOR_GREEN, SHAPE_COLOR_BLUE};

// Shape transparency
final char SHAPE_TRANSPARENCY_SOLID = 'S';
final char SHAPE_TRANSPARENCY_TRANSLUCENT = 'T';
final char SHAPE_TRANSPARENCY_OPEN = 'O';
final char[] SHAPE_TRANSPARENCIES = {SHAPE_TRANSPARENCY_SOLID, SHAPE_TRANSPARENCY_TRANSLUCENT, SHAPE_TRANSPARENCY_OPEN};

// Shape types
final char SHAPE_TYPE_DIAMOND = 'D';
final char SHAPE_TYPE_OVAL = 'O';
final char SHAPE_TYPE_RECTANGLE = 'R';
final char[] SHAPE_TYPES = {SHAPE_TYPE_DIAMOND, SHAPE_TYPE_OVAL, SHAPE_TYPE_RECTANGLE};
